Areas/User/Controllers/SetPasswordController.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ManagingRestaurant.Areas.User.Models;
using ManagingRestaurant.Models;
using ManagingRestaurant.Data;

namespace ManagingRestaurant.Areas.User.Controllers;

[Area("User")]
[Authorize(Roles = $"{RoleName.Administrator}")]
public class SetPasswordController : Controller
{
    private readonly RestaurantContext _context;
    private readonly UserManager<AppUser> _userManager;
    [TempData] public string StatusMessage { get; set; }

    public SetPasswordController(RestaurantContext context, UserManager<AppUser> userManager)
    {
        _context = context;
        _userManager = userManager;
    }
    
    [BindProperty]
    public SetPassModel model {set; get;}
    
    // GET: User/SetPassword/asdd-asdjv-asd
    public async Task<IActionResult> SetPassword(Guid? id)
    {
        if (id == null || _context.Users == null)
        {
            return NotFound();
        }

        var user = await _context.Users
            .FirstOrDefaultAsync(u => u.Id == id.ToString());
        
        model = new SetPassModel
        {
            Id = user.Id.ToString(),
            UserName = user.UserName,
            Email = user.Email,
            FullName = user.FullName,
            Image = string.IsNullOrEmpty(user.Image) ? "https://www.pngkey.com/png/full/72-729716_user-avatar-png-graphic-free-download-icon.png" : user.Image,
            Address = user.Address,
        };
        if (user == null)
        {
            return NotFound();
        }

        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SetPassword(
        [Bind("Id,Password,UserName,FullName,Email,Image,Address,Job,ConfirmedPassword")]
        SetPassModel setPassModel)
    {
        if (ModelState.IsValid)
        {
            
            var user = await _userManager.FindByIdAsync(setPassModel.Id);
            if (user != null)
            {
                var deletePass = user.PasswordHash != null ? await _userManager.RemovePasswordAsync(user) : IdentityResult.Success;
                if (deletePass.Succeeded)
                {
                    var addPass = await _userManager.AddPasswordAsync(user, setPassModel.Password);
                    if (addPass.Succeeded)
                    {
                        StatusMessage = "Password updated successfully.";
                        
                    }
                    else
                    {
                        StatusMessage = "Error: Password not updated.";
                    }
                    return RedirectToAction("Edit","Home",new {id = setPassModel.Id});
                }
            }
        }
        StatusMessage = "Error: Password not updated.";
        return View(setPassModel);
    }
}

Areas/User/Views/SetPassword/SetPassword.cshtml
@using ManagingRestaurant.Data
@using Microsoft.AspNetCore.Identity
@using Microsoft.EntityFrameworkCore
@model ManagingRestaurant.Areas.User.Models.SetPassModel
@inject UserManager<AppUser> _userManager;
@inject RestaurantContext _context;
@{
    ViewData["Title"] = "Set Password";
    Layout = "_LayoutAdmin";
}
<partial name="_StatusMessage"/>
<form class="m-3" asp-controller="SetPassword" asp-action="SetPassword" method="post">
  <section style="background-color: #eee;">
    <input asp-for="@Model.Id" class="disabled d-none"/>
    <input asp-for="@Model.UserName" class="disabled d-none"/>
    <input asp-for="@Model.Email" class="disabled d-none"/>
    <input asp-for="@Model.FullName" class="disabled d-none"/>
    <input asp-for="@Model.Image" class="disabled d-none"/>
    <input asp-for="@Model.Address" class="disabled d-none"/>
    <div class="container py-5">
      <div class="row">
        <div class="col">
          <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
            <ol class="breadcrumb mb-0 d-flex justify-content-between">
              <li>
                <button type="submit" class="btn btn-success mr-2">Save</button>
                <a class="btn btn-info mr-2" asp-controller="Home" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>

                <a asp-controller="Roles" asp-action="Roles" asp-route-id="@Model.Id" class="btn btn-warning">Set Role</a>
              </li>
              <li><button asp-controller="Home" asp-action="Index" class="btn btn-primary mr-2">Back To list</button></li>
            </ol>
          </nav>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
                            <img src="@Url.Content("~/UploadedFiles/" + Model.Image)" alt="avatar"
                   class="rounded-circle img-fluid" style="width: 150px;">
              <h5 class="my-3">@Model.UserName</h5>
              <p class="text-muted mb-1">@Model.FullName</p>
              <p class="text-muted mb-4">@Model.Address</p>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row align-items-center">
                <div class="col-sm-4">
                  <label class="mt-1 mr-3" asp-for="@Model.UserName"></label>
                </div>
                <div class="col-sm-8">
                  <p class="m-0">@Model.UserName</p>
                </div>
              </div>
              <hr>
              <div class="row align-items-center">
                <div class="col-sm-4">
                  <label class="mt-1 mr-3" asp-for="@Model.Email"></label>
                </div>
                <div class="col-sm-8">
                  <p class="m-0">@Model.Email</p>
                </div>
              </div>
              <hr>
              <div class="row align-items-center">
                <div class="col-sm-4">
                  <label class="mt-1 mr-3" asp-for="@Model.Password"></label>
                </div>
                <div class="col-sm-8">
                  <input asp-for="@Model.Password" class="form-control"/>
                  <span asp-validation-for="@Model.Password" class="text-danger"></span>
                </div>
              </div>
              <hr>
              <div class="row align-items-center">
                <div class="col-sm-4">
                  <label class="mt-1 mr-3" asp-for="@Model.ConfirmedPassword"></label>
                </div>
                <div class="col-sm-8">
                  <input asp-for="@Model.ConfirmedPassword" class="form-control"/>
                  <span asp-validation-for="@Model.ConfirmedPassword" class="text-danger"></span>
                </div>
              </div>
              
            </div>
          </div>

        </div>

      </div>
    </div>
  </section>
</form>